/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrafficLightsRouteImport } from './routes/traffic-lights'
import { Route as StopWatchRouteImport } from './routes/stop-watch'
import { Route as RockPaperScissorsRouteImport } from './routes/rock-paper-scissors'
import { Route as RandomQoutesRouteImport } from './routes/random-qoutes'
import { Route as GradientRouteImport } from './routes/gradient'
import { Route as DiceRouteImport } from './routes/dice'
import { Route as IndexRouteImport } from './routes/index'

const TrafficLightsRoute = TrafficLightsRouteImport.update({
  id: '/traffic-lights',
  path: '/traffic-lights',
  getParentRoute: () => rootRouteImport,
} as any)
const StopWatchRoute = StopWatchRouteImport.update({
  id: '/stop-watch',
  path: '/stop-watch',
  getParentRoute: () => rootRouteImport,
} as any)
const RockPaperScissorsRoute = RockPaperScissorsRouteImport.update({
  id: '/rock-paper-scissors',
  path: '/rock-paper-scissors',
  getParentRoute: () => rootRouteImport,
} as any)
const RandomQoutesRoute = RandomQoutesRouteImport.update({
  id: '/random-qoutes',
  path: '/random-qoutes',
  getParentRoute: () => rootRouteImport,
} as any)
const GradientRoute = GradientRouteImport.update({
  id: '/gradient',
  path: '/gradient',
  getParentRoute: () => rootRouteImport,
} as any)
const DiceRoute = DiceRouteImport.update({
  id: '/dice',
  path: '/dice',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dice': typeof DiceRoute
  '/gradient': typeof GradientRoute
  '/random-qoutes': typeof RandomQoutesRoute
  '/rock-paper-scissors': typeof RockPaperScissorsRoute
  '/stop-watch': typeof StopWatchRoute
  '/traffic-lights': typeof TrafficLightsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dice': typeof DiceRoute
  '/gradient': typeof GradientRoute
  '/random-qoutes': typeof RandomQoutesRoute
  '/rock-paper-scissors': typeof RockPaperScissorsRoute
  '/stop-watch': typeof StopWatchRoute
  '/traffic-lights': typeof TrafficLightsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dice': typeof DiceRoute
  '/gradient': typeof GradientRoute
  '/random-qoutes': typeof RandomQoutesRoute
  '/rock-paper-scissors': typeof RockPaperScissorsRoute
  '/stop-watch': typeof StopWatchRoute
  '/traffic-lights': typeof TrafficLightsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dice'
    | '/gradient'
    | '/random-qoutes'
    | '/rock-paper-scissors'
    | '/stop-watch'
    | '/traffic-lights'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dice'
    | '/gradient'
    | '/random-qoutes'
    | '/rock-paper-scissors'
    | '/stop-watch'
    | '/traffic-lights'
  id:
    | '__root__'
    | '/'
    | '/dice'
    | '/gradient'
    | '/random-qoutes'
    | '/rock-paper-scissors'
    | '/stop-watch'
    | '/traffic-lights'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DiceRoute: typeof DiceRoute
  GradientRoute: typeof GradientRoute
  RandomQoutesRoute: typeof RandomQoutesRoute
  RockPaperScissorsRoute: typeof RockPaperScissorsRoute
  StopWatchRoute: typeof StopWatchRoute
  TrafficLightsRoute: typeof TrafficLightsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/traffic-lights': {
      id: '/traffic-lights'
      path: '/traffic-lights'
      fullPath: '/traffic-lights'
      preLoaderRoute: typeof TrafficLightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stop-watch': {
      id: '/stop-watch'
      path: '/stop-watch'
      fullPath: '/stop-watch'
      preLoaderRoute: typeof StopWatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rock-paper-scissors': {
      id: '/rock-paper-scissors'
      path: '/rock-paper-scissors'
      fullPath: '/rock-paper-scissors'
      preLoaderRoute: typeof RockPaperScissorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/random-qoutes': {
      id: '/random-qoutes'
      path: '/random-qoutes'
      fullPath: '/random-qoutes'
      preLoaderRoute: typeof RandomQoutesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gradient': {
      id: '/gradient'
      path: '/gradient'
      fullPath: '/gradient'
      preLoaderRoute: typeof GradientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dice': {
      id: '/dice'
      path: '/dice'
      fullPath: '/dice'
      preLoaderRoute: typeof DiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DiceRoute: DiceRoute,
  GradientRoute: GradientRoute,
  RandomQoutesRoute: RandomQoutesRoute,
  RockPaperScissorsRoute: RockPaperScissorsRoute,
  StopWatchRoute: StopWatchRoute,
  TrafficLightsRoute: TrafficLightsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
